### ISSUE TITLE
API Rename Failing

### ISSUE THREAD

**Issue by Minxster** [Unmanic/plugin.notify_sonarr#3]
Hi, I'm new to UnManic (and Sonarr for that matter). But I'm trying to use this plugin to refresh then rename newly transcoded files. But I seem to be getting these messages for the logs of both products:

Sonarr Debug Log:
```
2023-06-16 00:07:10.6|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2023-06-16 00:07:10.6|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=true: 200.OK (1 ms)
2023-06-16 00:07:10.7|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2023-06-16 00:07:10.7|Debug|Api|[GET] /api/v3/queue?page=1&pageSize=20&sortDirection=ascending&sortKey=timeleft&includeUnknownSeriesItems=true: 200.OK (0 ms)
2023-06-16 00:07:13.9|Debug|Api|[GET] /api/rename?seriesId=293: 404.NotFound (0 ms)
```

UnManic Logs:
```
2023-06-16T00:07:03:INFO:Unmanic.Plugin.notify_sonarr - Successfully queued refresh of the Series '293' for file: '/mnt/truenas_raidz/TV/All TV Shows/NCIS Los Angeles/Series 14/NCIS - Los Angeles - S14E21 - New Beginnings (2) - WEBDL-1080p - ETHEL.mkv'
2023-06-16T00:07:13:ERROR:Unmanic.Plugin.notify_sonarr - Failed to trigger rename of series 'NCIS: Los Angeles' for file: '/mnt/truenas_raidz/TV/All TV Shows/NCIS Los Angeles/Series 14/NCIS - Los Angeles - S14E21 - New Beginnings (2) - WEBDL-1080p - ETHEL.mkv'
2023-06-16T00:07:13:ERROR:Unmanic.Plugin.notify_sonarr - Resource not found
```

I am using the v4 (development) branch on Sonar, if this makes any difference?

**Comment by Minxster** [comment]
I'm pretty much as noobie at all of this, but can the plugin.py we altered, at the very least, to have this:

`rename_list = api.request_get("v3/rename", "", params={"seriesId": {series_id}})`

I manually updated this in my container and restarted it and now it's actually renaming the whole season, which is fine, I'd rather it only did 1 episode, but at least the rename is working? 😁

**Comment by RoyalNautilus** [comment]
Having this issue as well. Haven't had a chance to dig into the logs but can tell from file metadata and results that Unmanic is successfully notifying Sonarr of the new file info, but files are not being renamed by the plugin.

**Comment by Minxster** [comment]
I actually kinda gave-up on this... I removed the scheduling for scanning my library from within UnManic, so now I trigger this with an API call. The file format (mp4, mkv) is just kept the same, in UnManic, so Sonarr doesn't really need to know much in the way of a rename. Sonarr (and Radarr for that matter) just pick up the file change when it does it's own scans.... This isn't ideal at all, but it was only way I could use UnManic without the need to trigger Sonarr to look at the new file(s).

TBH, once I transcoded my whole media library, I stopped transcoding (looking to transcode) files in my general show and movies folders. The only one I keep running is transcoding my DVR files, which only affects Plex. Mainly because I couldn't fix the 265 compression artifacts that would appear in most files, usually when the camera moves and artifacts appear from the bottom of the screen and move up. This isn't UnManic's fault, it's more to do with compression settings that I couldn't fix. But I did get used to this compression issue since I saved so much space.

By comparison, I spent a lot of time in Sonarr looking to use 'Custom Formats', so that 265 encoded files are prioritised, by way of the score. This actually helps a lot with all of this as I get 265 files without the issue of compression artifacts.

**Comment by GlenNicholls** [comment]
Experiencing the same issue, appears to be some discord support on the topic as well https://discord.com/channels/819327740279914516/1215175464243699772/1215175468114903120

EDIT: temporary manual workaround is to: go to series tab, select all/desired titles, and click "Rename". This will also correctly update the file name for external files like `.srt` and `.nfo`.

EDIT2: I thought this might be related to unmanic and sonarr having different path mappings (e.g. `/library` vs. `/data`) for the error `Failed to trigger rename of series`. I changed unmanic to use the same volume mapping and the same failure as the original issue description persists.

**Comment by GlenNicholls** [comment]
In @Minxster description, shouldn't `/api/rename?seriesId=293` instead be `/api/v3/rename?seriesId=293`? Seems like the API request is being rejected and https://sonarr.tv/docs/api/#/RenameEpisode aligns with this. 

I think the API URL for the `rename` is just wrong. I glanced at Unmanic's codebase and it's not immediately obvious to me where this is happening, but this is a good starting point I think

**Comment by Minxster** [comment]
@GlenNicholls yes, that's the change I ended up making:
[My comment with fixed/update line](https://github.com/Unmanic/plugin.notify_sonarr/issues/3#issuecomment-1597099008)

As I'm using this in docker, it was bit more difficult to alter, and I'm not sure on how permanent the change actually is, but it was working when I changed it.

I used a console connection into the container and tracked my way through to the plugins folder and found the correct `plugin.py`. The line you need to alter isn't in UnManic's codebase, but in the plugin 😉👍
[Link to line the needs altering](https://github.com/Unmanic/plugin.notify_sonarr/blob/7ab9daf3076a73b058729289b359c6eb622b3cc2/plugin.py#L163C1-L163C90)

**Comment by GlenNicholls** [comment]
Yeah, I noticed that after I posted my comment. I currently have the config mapped so the change to that plugin persists a container reboot.

It looks like the `Pyarr 3.0.1` dependency is quite old (similar for `notify_radarr`) as the latest for that package is currently at `v5` which explains why I struggled to find some of the methods in `plugin.py`. I'm guessing that the v3 API issue originates in that package and has since been fixed, but there's probably a fair bit of refactoring required in this plugin due to breaking changes introduced in that package since `3.0.1`.

**Comment by GlenNicholls** [comment]
Looks like https://github.com/Unmanic/plugin.notify_sonarr/compare/master...Quack6765:plugin.notify_sonarr:master might already be handling this

**Comment by Minxster** [comment]
@GlenNicholls I just had a quick look and saw this:
[Pull Request](https://github.com/Unmanic/plugin.notify_sonarr/pull/4)

It seems that folk are looking at this, just no idea when they're going to commit the pull request. Hopefully you've managed to get around the issue just now?
